name: Deploy Documentation Site
on: [push]
jobs:
  deploy-documentation-site:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: docs-cd
          folder: docs
